### ISSUE TITLE
seems to only work when Obsidian is in the background

### ISSUE THREAD

**Issue by chrisgrieser** [valentine195/obsidian-notifier#1]
When Obsidian is the frontmost app, it still shows notices.

```
macOS 12.2.1
Obsidian 0.14.2
```

**Comment by valentine195** [comment]
You want it to always use the OS notifications?

i actually explicitly set it to not use system notifications if the obsidian window is focused

**Comment by chrisgrieser** [comment]
Yeah, or at least have a toggle for it. 

Like when I setup sounds for Obsidian notifications, it's actually a bit weird when they do not make signs anymore when focused etc

**Comment by valentine195** [comment]
Closed in 0.0.3
